version: 2
jobs:
  build:
    docker:
    - image: google/cloud-sdk
    steps:
    - setup_remote_docker
    - checkout
    - run:
        name: Store Service Account
        command: echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
    - run: |
        gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
        gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
        gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
        cd hello-app
        export PROJECT_ID="$(gcloud config get-value project -q)"
        echo $PROJECT_ID
        docker build -t gcr.io/${PROJECT_ID}/hello-app:v1 .
        docker images
        gcloud auth configure-docker
        docker push gcr.io/${PROJECT_ID}/hello-app:${DOCKER_IMAGE_VERSION}
        #gcloud container clusters create hello-cluster --num-nodes=2
        gcloud container clusters create ${GOOGLE_KUBER_NAME}  -num-nodes=2 --labels ${GOOGLE_KUBER_LABLES}
        kubectl run hello-web --image=gcr.io/${PROJECT_ID}/hello-app:${DOCKER_IMAGE_VERSION} --port 8080
        kubectl get pods
        kubectl expose deployment hello-web --type=LoadBalancer --port 80 --target-port 8080
      #  gcloud compute instances create ${GOOGLE_VM_NAME} --image-family ${GOOGLE_VM_FAMILY} --image-project ${GOOGLE_VM_IMAGE} --labels ${GOOGLE_VM_LABELS}
      #  gcloud compute instances list
workflows:
  version: 2
  workflow:
    jobs:
    - build:
       filters:
            branches:
              only: master
