version: 2
jobs:
  build:
    docker:
    - image: google/cloud-sdk
    steps:
    - checkout
    - run:
        name: Store Service Account
        command: echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
    - run: |
        gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
        gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
        gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
     #   ls
  workflows:
  version: 2
  workflow:
    jobs:
    - build:
       filters:
            branches:
              only: master
